### ISSUE TITLE
[feat] 설명 피드백 사항

### ISSUE THREAD

**Issue by hanseulhee** [primus-teoSprint/FE#56]
### ❤️‍🔥 어떤 개발 사항인가요?

- [ ] 도움말 설명을 복사 붙혀넣기 하고 싶은데 손가락을 내리면 없어진다.
- [ ] 전체 이용자 수에 대한 설명
- [ ] 체크 박스 설명

### ✍🏻 TODO

- [ ] 피드백 반영

**Comment by XionWCFM** [comment]
헉 마치 제 피드백 같이 생겼내요 🔥

**Comment by hanseulhee** [comment]
@XionWCFM 다 해결하겟슴니다 😎

**Comment by XionWCFM** [comment]
언제 고쳐지나요?? 고쳐질떄까지 숨 참겠읍니다 흐으으읍!!!!!

**Comment by hanseulhee** [comment]
@XionWCFM 2주만.. 기달 ~~
